### PR TITLE
Do not include intrinsics header when building with NVCC

### PR DESCRIPTION
**Pull request by drbenmorgan**
Reported through upstream use in VecGeom CUDA-enabled builds. Under certain combinations of GCC and NVCC, use of VecCore in VecGeom CUDA code gives build failures with undefined identifier errors, e.g.

```
.../lib/gcc/x86_64-pc-linux-gnu/9.4.0/include/avx512fintrin.h(9146): error: identifier "__builtin_ia32_rndscaless_round" is undefined
```

Triaged to inclusion of the `x86intrin.h` and seemingly known issues between this and NVCC, e.g. https://github.com/NixOS/nixpkgs/issues/103415. No clear answer found on which versions of GCC/NVCC this is resolved in.

Do not include the system intrinsics header in SIMD.h when NVCC is the compiler to workaround GCC/NVCC incompatibilities here. Tests of both VecCore and upstream use in VecGeom pass both in Vector and Cuda modes.

Pinging also @sethrj @pcanal for their info.

### CODE REVIEW

**Comment by amadio** [comment]
Looks like CDash is not liking connections from outside CERN. I will need to make a change to the CI to stop posting results there. This sort of problem is usually a bug with CUDA and should be reported to Nvidia [here](https://developer.nvidia.com/nvidia_bug/add) (you will need to register an account to do so, see [this bug](https://developer.nvidia.com/nvidia_bug/3551253) as an example of similar bug I've filed before). However, given how common this kind of problem is, and since there is no harm I can see while compiling VecGeom with Vc backend and CUDA enabled at the same time, I will add an equivalent change to this pull request once I get the CI problems sorted out.

**Comment by sethrj** [comment]
@amadio It looks to me as though VecCore is trying to include a nonstandard header `x86intrin.h` without testing if it's available or working for the given compiler. There's an exception for the MSVC compiler; it makes sense to me that you'd have similar exceptions for other compilers as well.

**Comment by amadio** [comment]
> @amadio It looks to me as though VecCore is trying to include a nonstandard header x86intrin.h without testing if it's available or working for the given compiler.

The [`x86intrin.h`](https://github.com/gcc-mirror/gcc/blob/master/gcc/config/i386/x86intrin.h) header is a GCC convenience header that includes the standard headers so you don't have to remember if you have to include `xmmintrin.h` or `emmintrin.h` or `immintrin.h`, etc. On Windows, MSVC has a similar header, but it's called just [`intrin.h`](https://learn.microsoft.com/en-us/cpp/intrinsics/x64-amd64-intrinsics-list?view=msvc-170), that's why we have to check for MSVC and choose the right one. NVCC works with GCC, so merely including these headers is not a bug. NVCC needs to be able to handle intrinsics code on the host side, if it doesn't, then it's a bug. You may have to include the SIMD headers when developing code using both SIMD and CUDA in the same program.

**Comment by sethrj** [comment]
@amadio NVCC uses libstdc++ (distributed with GCC) for standard library code compiled with NVCC, and it dispatches host code to GCC.  The availability of any of the SIMD intrinsic header files to NVCC is I think incidental and not indicative of support for it.

The error stems from the fact that NVCC is a different *compiler* to GCC: when building for device compilation, it doesn't support the same set of compiler intrinsics as GCC, so functions that `xmmintrin.h` assume exist are in fact undefined. There shouldn't be any requirement for one compiler to implement another compiler's private compiler intrinsics, so it should be the downstream library writer's job to guard compiler-specific includes so that they're only used by the correct compiler.

**Comment by drbenmorgan** [comment]
Dumb question, but is that include of the intrinsics even needed? I can't find any _obvious_ use of intrinsics directly in VecCore, but could well be missing something...

**Comment by amadio** [comment]
I just wanted to make inclusion of VecCore enable SIMD intrinsics by default, but I guess you are right, I can probably remove it and sidestep these problems since VecCore itself is not using that directly, but only via Vc and other libraries. I use AVX2 intrinsics in a test, but I can just include `x86intrin.h` there instead of the main headers. I will do it and close this when I merge the patch. If you want a patch release for this, I can create one tomorrow.

**Comment by drbenmorgan** [comment]
@amadio, I've tested the current `master` against the known failing GCC/NVCC case and it does resolve the issue - so I think that change is good to go for a patch release.

**Comment by amadio** [comment]
Thanks, I've released [v0.8.1](https://github.com/root-project/veccore/releases/tag/v0.8.1), so closing this.

**Comment by sethrj** [comment]
Thanks @amadio for the fix and version bump!

**Pull request closed without merging**
