### PR TITLE
Update to gtest 1.10.0

### PR DESCRIPTION
**Pull request by bernhardmgruber**

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
The Windows CI is likely needing `gtest_force_shared_crt=ON`. Where do I set that?

**Comment by amadio** [comment]
Looks like this update introduces a lot of warnings from gtest, for things that they have deprecated, so VecCore needs changes before this update (or together with it) to make it worth updating. I am also thinking about trying an approach with git submodules instead of having gtest source code in VecCore's repo like this.

**Comment by amadio** [comment]
I also think that the type renaming is not necessary inside gtest, it's probably a search/replace mistake that I missed.

**Comment by oshadura** [comment]
@bernhardmgruber coool! I will say we can merge it since it is green, but I was curious (cc: @amadio ) why not to remove to  gtest sources and add it via `ExternalProject_Add()` like it is done in ROOT for example: https://github.com/root-project/root/blob/master/cmake/modules/SearchInstalledSoftware.cmake#L1701-L1789

**Comment by bernhardmgruber** [comment]
Personally, I would also just remove gtest and add it just via `find_package`. I do not like `ExternalProject_Add()` because IMO CMake should install dependencies. That's what package managers are for. And gtest should be widely available.

I think the reason why gtest is added locally was because it needed custom patches. This is less relevant now, but we need to configure one option that otherwise users would need to set themselves (Totally fine for me! But changes behavior).

**Comment by amadio** [comment]
Wait, why did @pcanal assign this to you, @oshadura? I don't understand.

In VecCore, I needed to patch gtest to make it work back in the day, and after that I didn't really see the need to update it.
Now it's quite old, and should be updated, but using `ExternalProject_Add()` is not a good idea in my opinion. It mixes very badly with other targets within the same project and requires a lot of ugly hacking as can be seen in the ROOT code linked above, where targets from gtest have to be recreated by hand, etc. It's just not worth it. I think that @bernhardmgruber's suggestion is what I will go for in the end (just remove gtest and use `find_package()`), and ensure it's properly installed by CI scripts before VecCore. However, system versions of gtest are not good enough (i.e. via package managers) because VecCore needs to be tested with many different compilers, and their ABIs aren't always compatible, so gtest must be compiled with the same compiler that VecCore is being tested with to avoid linking failures due to mismatched ABI. Both Clang and ICC had issues due to that in the past. In fact, this was *the* major reason to add gtest sources to the repository rather than picking it up externally. Also gtest is special in that it is meant to be added like this to other projects for testing purposes. Real dependencies (like Vc and UME::SIMD for VecCore) really shouldn't be vendored. I only do that to facilitate testing in CI due to the same reasons about ABI, but I discourage people from using those options when installing VecCore. In any case, I will handle the update of gtest myself, as that will also require fixing a lot of warnings on VecCore's side for interfaces that are deprecated in newer versions of gtest.

**Comment by oshadura** [comment]
> Wait, why did @pcanal assign this to you, @oshadura? I don't understand.

I think @pcanal didn't notice that it is veccore and not root.git :+1: (I was just going through all emails piled over Christmas break).

**Comment by bernhardmgruber** [comment]
@amadio if linking with gtest is an issue, you could also switch to a header only testing framework. At CASUS and HZDR, we use Catch2 a lot. Although my personal favorite is still gtest.

**Comment by amadio** [comment]
@oshadura Makes sense...

@bernhardmgruber Header only usually means longer compile times. It would also be a lot of work to convert all templated tests from gtest to something else, it's not really worth the investment.

**Comment by pcanal** [comment]
>Wait, why did @pcanal assign this to you, @oshadura? I don't understand.

My bad.  I mis-read the project (i.e. did not notice it was in veccore).  Sorry about that.

**Comment by amadio** [comment]
No problem, I was just confused.

**Comment by amadio** [comment]
I finally took some time to update both GoogleTest and Google Benchmark, and also added options to only enable those when needed, allowing to use an external version if available. I've moved them to use the same system as for Vc and UME::SIMD, so that now all bundled dependencies use the same style. Closing this pull request, as it's not needed anymore. Thanks a lot for the effort, that motivated me to finally do this! Cheers,

**Pull request closed without merging**
